### ISSUE TITLE
cannot import name 'cache_ops' from 'vllm'

### ISSUE THREAD

**Issue by iateadonut** [huggingface/text-generation-inference#1325]
### System Info

$ text-generation-launcher --env
Runtime environment:
Target: x86_64-unknown-linux-gnu
Cargo version: 1.70.0
Commit sha: 3238c49121b02432bf2938c6ebfd44f06c5adc2f
Docker label: N/A
nvidia-smi:
Mon Dec 11 00:12:49 2023       
```
   +---------------------------------------------------------------------------------------+
   | NVIDIA-SMI 535.104.12             Driver Version: 535.104.12   CUDA Version: 12.2     |
   |-----------------------------------------+----------------------+----------------------+
   | GPU  Name                 Persistence-M | Bus-Id        Disp.A | Volatile Uncorr. ECC |
   | Fan  Temp   Perf          Pwr:Usage/Cap |         Memory-Usage | GPU-Util  Compute M. |
   |                                         |                      |               MIG M. |
   |=========================================+======================+======================|
   |   0  NVIDIA GeForce RTX 4090        On  | 00000000:01:00.0 Off |                  Off |
   |  0%   40C    P8              32W / 450W |   8488MiB / 24564MiB |      0%      Default |
   |                                         |                      |                  N/A |
   +-----------------------------------------+----------------------+----------------------+
                                                                                            
   +---------------------------------------------------------------------------------------+
   | Processes:                                                                            |
   |  GPU   GI   CI        PID   Type   Process name                            GPU Memory |
   |        ID   ID                                                             Usage      |
   |=======================================================================================|
   |    0   N/A  N/A      1053      G   /usr/lib/xorg/Xorg                           18MiB |
   |    0   N/A  N/A      3068      C   ...vateGPT/conda_privateGPT/bin/python     8454MiB |
   +---------------------------------------------------------------------------------------+
```

$ cargo version
cargo 1.69.0 (6e9a83356 2023-04-12)

model: https://huggingface.co/mistralai/Mistral-7B-Instruct-v0.1

### Information

- [ ] Docker
- [X] The CLI directly

### Tasks

- [X] An officially supported command
- [ ] My own modifications

### Reproduction

$ text-generation-launcher --model-id mistralai/Mistral-7B-Instruct-v0.1 --port 8080

2023-12-10T15:11:36.466940Z  INFO text_generation_launcher: Args { model_id: "mistralai/Mistral-7B-Instruct-v0.1", revision: None, validation_workers: 2, sharded: None, num_shard: None, quantize: None, dtype: None, trust_remote_code: false, max_concurrent_requests: 128, max_best_of: 2, max_stop_sequences: 4, max_top_n_tokens: 5, max_input_length: 1024, max_total_tokens: 2048, waiting_served_ratio: 1.2, max_batch_prefill_tokens: 4096, max_batch_total_tokens: None, max_waiting_tokens: 20, hostname: "0.0.0.0", port: 8080, shard_uds_path: "/tmp/text-generation-server", master_addr: "localhost", master_port: 29500, huggingface_hub_cache: None, weights_cache_override: None, disable_custom_kernels: false, cuda_memory_fraction: 1.0, rope_scaling: None, rope_factor: None, json_output: false, otlp_endpoint: None, cors_allow_origin: [], watermark_gamma: None, watermark_delta: None, ngrok: false, ngrok_authtoken: None, ngrok_edge: None, env: false }
2023-12-10T15:11:36.467204Z  INFO download: text_generation_launcher: Starting download process.
2023-12-10T15:11:41.156867Z  INFO text_generation_launcher: Files are already present on the host. Skipping download.

2023-12-10T15:11:41.776149Z  INFO download: text_generation_launcher: Successfully downloaded weights.
2023-12-10T15:11:41.776560Z  INFO shard-manager: text_generation_launcher: Starting shard rank=0
2023-12-10T15:11:46.207192Z  WARN text_generation_launcher: Could not import Flash Attention enabled models: cannot import name 'cache_ops' from 'vllm' (/mnt/models/text-generation-inference/conda_tgi/lib/python3.9/site-packages/vllm/__init__.py)

2023-12-10T15:11:46.209404Z  WARN text_generation_launcher: Could not import Mistral model: cannot import name 'cache_ops' from 'vllm' (/mnt/models/text-generation-inference/conda_tgi/lib/python3.9/site-packages/vllm/__init__.py)

2023-12-10T15:11:46.652524Z ERROR text_generation_launcher: Error when initializing model
Traceback (most recent call last):
  File "/mnt/models/text-generation-inference/conda_tgi/bin/text-generation-server", line 8, in <module>
    sys.exit(app())
  File "/mnt/models/text-generation-inference/conda_tgi/lib/python3.9/site-packages/typer/main.py", line 311, in __call__
    return get_command(self)(*args, **kwargs)
  File "/mnt/models/text-generation-inference/conda_tgi/lib/python3.9/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
  File "/mnt/models/text-generation-inference/conda_tgi/lib/python3.9/site-packages/typer/core.py", line 778, in main
    return _main(
  File "/mnt/models/text-generation-inference/conda_tgi/lib/python3.9/site-packages/typer/core.py", line 216, in _main
    rv = self.invoke(ctx)
  File "/mnt/models/text-generation-inference/conda_tgi/lib/python3.9/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/mnt/models/text-generation-inference/conda_tgi/lib/python3.9/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/mnt/models/text-generation-inference/conda_tgi/lib/python3.9/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
  File "/mnt/models/text-generation-inference/conda_tgi/lib/python3.9/site-packages/typer/main.py", line 683, in wrapper
    return callback(**use_params)  # type: ignore
  File "/mnt/models/text-generation-inference/server/text_generation_server/cli.py", line 83, in serve
    server.serve(
  File "/mnt/models/text-generation-inference/server/text_generation_server/server.py", line 207, in serve
    asyncio.run(
  File "/mnt/models/text-generation-inference/conda_tgi/lib/python3.9/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/mnt/models/text-generation-inference/conda_tgi/lib/python3.9/asyncio/base_events.py", line 634, in run_until_complete
    self.run_forever()
  File "/mnt/models/text-generation-inference/conda_tgi/lib/python3.9/asyncio/base_events.py", line 601, in run_forever
    self._run_once()
  File "/mnt/models/text-generation-inference/conda_tgi/lib/python3.9/asyncio/base_events.py", line 1905, in _run_once
    handle._run()
  File "/mnt/models/text-generation-inference/conda_tgi/lib/python3.9/asyncio/events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
> File "/mnt/models/text-generation-inference/server/text_generation_server/server.py", line 159, in serve_inner
    model = get_model(
  File "/mnt/models/text-generation-inference/server/text_generation_server/models/__init__.py", line 261, in get_model
    raise NotImplementedError("Mistral model requires flash attention v2")
NotImplementedError: Mistral model requires flash attention v2

2023-12-10T15:11:47.286995Z ERROR shard-manager: text_generation_launcher: Shard complete standard error output:

Traceback (most recent call last):

  File "/mnt/models/text-generation-inference/conda_tgi/bin/text-generation-server", line 8, in <module>
    sys.exit(app())

  File "/mnt/models/text-generation-inference/server/text_generation_server/cli.py", line 83, in serve
    server.serve(

  File "/mnt/models/text-generation-inference/server/text_generation_server/server.py", line 207, in serve
    asyncio.run(

  File "/mnt/models/text-generation-inference/conda_tgi/lib/python3.9/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)

  File "/mnt/models/text-generation-inference/conda_tgi/lib/python3.9/asyncio/base_events.py", line 647, in run_until_complete
    return future.result()

  File "/mnt/models/text-generation-inference/server/text_generation_server/server.py", line 159, in serve_inner
    model = get_model(

  File "/mnt/models/text-generation-inference/server/text_generation_server/models/__init__.py", line 261, in get_model
    raise NotImplementedError("Mistral model requires flash attention v2")

NotImplementedError: Mistral model requires flash attention v2
 rank=0
2023-12-10T15:11:47.381222Z ERROR text_generation_launcher: Shard 0 failed to start
2023-12-10T15:11:47.381265Z  INFO text_generation_launcher: Shutting down shards
Error: ShardCannotStart

### Expected behavior

I expect the server to start.

Instead, these are the two main error messages I get:

2023-12-10T15:11:46.207192Z  WARN text_generation_launcher: Could not import Flash Attention enabled models: cannot import name 'cache_ops' from 'vllm' (/mnt/models/text-generation-inference/conda_tgi/lib/python3.9/site-packages/vllm/__init__.py)

2023-12-10T15:11:46.209404Z  WARN text_generation_launcher: Could not import Mistral model: cannot import name 'cache_ops' from 'vllm' (/mnt/models/text-generation-inference/conda_tgi/lib/python3.9/site-packages/vllm/__init__.py)

I've gone into the server/ directory and installed each make file.

**Comment by Fyuzn** [comment]
It might be that the version of vllm is incorrect. You can try installing vllm version 0.2.0.

**Comment by deepily** [comment]
> It might be that the version of vllm is incorrect. You can try installing vllm version 0.2.0.

My experience is similar, both when attempting to build local version (v1.3.4/main branch) from CLI and after building Docker image locally and attempting to run it. After updating to v0.2.0 of vllm, the import error is resolved for both contexts.

**Comment by J1shen** [comment]
Hello, I encounter the same problem. But when I try to use vllm=0.2.0, I find it seems not to support cuda 12. So how can I solve it?
